import {useState} from "react";
function App(){
    const [count,setCount]=useState(0);
    //setCount is not inbuilt ,it is function generated by react
    /*
    internally happening this
    we can use another variable like newCount
    let count=0;
    function setCount(newvalue){
         count=newvalue;
    }
    */
    // increase
    const increase=()=>{
        setCount(count+1);
    }
    // decrese
    const decrease=()=>setCount(count-1)
    //multiply
    const multiply=()=>setCount(count*2)
    return (
        <div>
            <button onClick={increase}>increase</button>
            <button onClick={decrease}>decrease</button>
            <h1>{count}</h1>

        </div>
    )
}
export default App;